#### Server 세팅 ####
server:
  # Tomcat Server Port Setting
  port: 9999
  # JSP 수정 시 서버 재시작 없이 적용
  servlet:
    jsp:
      registered: true
    # 서버 인코딩 세팅
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

## 암호화
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#    password: 5678

#### Spring 세팅 ####
spring:
  # Mybatis 연결
  datasource:
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@localhost:8629:tbtest
    username: sys
    password: 1234
  # 부트 시 중복 Bean 에러 해결
  main:
    allow-bean-definition-overriding: true
  # 자동 리펙토링 (수정 시 즉각 반영) _ w
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  freemarker:
    cache: false
  mvc:
    converters:
      preferred-json-mapper: gson

#### Mybatis 세팅 ####
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: mappers/*.xml
