#### Server 세팅 ####
server:
  # Tomcat Server Port Setting
  port: 9999
  # JSP 수정 시 서버 재시작 없이 적용
  servlet:
    jsp:
      registered: true
    # 서버 인코딩 세팅
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

### 암호화 ####
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
#    password: 5678

#### Spring 세팅 ####
spring:
  # Mybatis 연결
  datasource:
    tomcat:
      max-wait: 10000
      max-active: 50
      test-on-borrow: true
    hikari:
      jdbc-url: ENC(T/qeLJY8CKGJPCc8N5YoEiG/5grDA0JNibDL/BbNCbmt2lbKsrkVo97XgLfGaj+z)
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      username: ENC(BURCKEnbZFZS4FFwgwDpWA==)
      password: ENC(pw1HnsuThMVw0tsywAdhLw==)

  # 부트 시 중복 Bean 에러 해결
  main:
    allow-bean-definition-overriding: true
  # 자동 리펙토링 (수정 시 즉각 반영) _ w
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  freemarker:
    cache: false
  # MyBatis Json 형식
  mvc:
    converters:
      preferred-json-mapper: gson
  # JDBC Platform 설정
  sql:
    init:
      platform: tibero

#### Mybatis 세팅 ####
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: mappers/*.xml
